title: Karthik Padmanabhan
description: Principal Software Engineer & Game Developer
url: https://karthikpadmanabhan.com
permalink: /blog/:year/:month/:day/:title/

# Exclude local/dev files from build
exclude:
  - README.md
  - readme.md
  - local/
  - Profile.pdf
  - workspace.code-workspace
